[package]
name = "yaml_test_creator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand ="0.9.1"
ratatui = { version= "0.29.0", features =["crossterm"]}
serde = { version = "1.0", features= ["derive"]}
serde_yaml = "0.8.26"
